import { ethers, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

const VOTING_DELAY = 1;
const VOTING_PERIOD = 300;
const PROPOSAL_THRESHOLD = 0;
const QUORUM_FRACTION = 4;
const TIMELOCK_MIN_DELAY = 300;
const DEMO_TREASURY_VALUE = 101;

function writeJson(filePath: string, value: unknown) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(value, null, 2));
}

function updateFrontendLocalEnv(addresses: {
  token: string;
  timelock: string;
  governor: string;
  treasury: string;
}) {
  const envPath = path.join(__dirname, "..", "..", "frontend", ".env.local");
  const managedKeys = new Set([
    "VITE_CHAIN_ID",
    "VITE_TOKEN_ADDRESS",
    "VITE_TIMELOCK_ADDRESS",
    "VITE_GOVERNOR_ADDRESS",
    "VITE_TREASURY_ADDRESS",
  ]);
  const existingLines = fs.existsSync(envPath)
    ? fs
        .readFileSync(envPath, "utf8")
        .split(/\r?\n/)
        .filter((line) => {
          const key = line.split("=")[0];
          return line.trim().length > 0 && !managedKeys.has(key);
        })
    : [];

  const localLines = [
    "VITE_CHAIN_ID=31337",
    `VITE_TOKEN_ADDRESS=${addresses.token}`,
    `VITE_TIMELOCK_ADDRESS=${addresses.timelock}`,
    `VITE_GOVERNOR_ADDRESS=${addresses.governor}`,
    `VITE_TREASURY_ADDRESS=${addresses.treasury}`,
  ];

  fs.writeFileSync(
    envPath,
    [
      "# Generated by `npm run demo:localhost` in contracts/.",
      ...existingLines,
      ...localLines,
    ].join("\n") + "\n"
  );
}

async function mineBlocks(count: number) {
  await network.provider.send("hardhat_mine", [`0x${count.toString(16)}`]);
}

async function main() {
  if (network.name !== "localhost") {
    throw new Error("Run this script with --network localhost.");
  }

  const signers = await ethers.getSigners();
  if (signers.length < 11) {
    throw new Error("The local demo needs at least 11 Hardhat accounts.");
  }

  const [deployer, ...voters] = signers.slice(0, 11);
  const voterShare = ethers.parseUnits("10000", 18);

  console.log("Deploying local governance demo...");
  console.log("Deployer:", deployer.address);

  const GovernanceToken = await ethers.getContractFactory("GovernanceToken");
  const token = await GovernanceToken.deploy(deployer.address);
  await token.waitForDeployment();

  const TimelockController = await ethers.getContractFactory(
    "TimelockController"
  );
  const timelock = await TimelockController.deploy(
    TIMELOCK_MIN_DELAY,
    [],
    [],
    deployer.address
  );
  await timelock.waitForDeployment();

  const DAOGovernor = await ethers.getContractFactory("DAOGovernor");
  const governor = await DAOGovernor.deploy(
    await token.getAddress(),
    await timelock.getAddress(),
    VOTING_DELAY,
    VOTING_PERIOD,
    PROPOSAL_THRESHOLD,
    QUORUM_FRACTION
  );
  await governor.waitForDeployment();

  const Treasury = await ethers.getContractFactory("Treasury");
  const treasury = await Treasury.deploy(await timelock.getAddress());
  await treasury.waitForDeployment();

  const PROPOSER_ROLE = await timelock.PROPOSER_ROLE();
  const CANCELLER_ROLE = await timelock.CANCELLER_ROLE();
  const EXECUTOR_ROLE = await timelock.EXECUTOR_ROLE();
  const DEFAULT_ADMIN_ROLE = await timelock.DEFAULT_ADMIN_ROLE();

  await (await timelock.grantRole(PROPOSER_ROLE, await governor.getAddress())).wait();
  await (await timelock.grantRole(CANCELLER_ROLE, await governor.getAddress())).wait();
  await (await timelock.grantRole(EXECUTOR_ROLE, ethers.ZeroAddress)).wait();
  await (await timelock.renounceRole(DEFAULT_ADMIN_ROLE, deployer.address)).wait();

  await (await token.connect(deployer).delegate(deployer.address)).wait();

  console.log("Funding and delegating 10 voter accounts...");
  for (const voter of voters) {
    await (await token.connect(deployer).transfer(voter.address, voterShare)).wait();
    await (await token.connect(voter).delegate(voter.address)).wait();
  }

  const targets = [await treasury.getAddress()];
  const values = [0n];
  const calldatas = [
    treasury.interface.encodeFunctionData("store", [DEMO_TREASURY_VALUE]),
  ];
  const title = "Hardhat demo: 10 accounts vote For";
  const description = `${title}\n\nThis local proposal is created by scripts/local-demo.ts. Ten delegated Hardhat accounts vote For, then the proposal is queued and executed through the timelock.`;
  const descriptionHash = ethers.keccak256(ethers.toUtf8Bytes(description));

  const proposalId = await governor
    .connect(deployer)
    .propose.staticCall(targets, values, calldatas, description);
  const proposeTx = await governor
    .connect(deployer)
    .propose(targets, values, calldatas, description);
  await proposeTx.wait();

  await mineBlocks(VOTING_DELAY + 1);

  console.log("Casting 10 For votes...");
  const voteTxHashes: string[] = [];
  for (const voter of voters) {
    const tx = await governor
      .connect(voter)
      .castVoteWithReason(proposalId, 1, "Local Hardhat demo approval");
    voteTxHashes.push(tx.hash);
    await tx.wait();
  }

  const [againstVotes, forVotes, abstainVotes] =
    await governor.proposalVotes(proposalId);

  await mineBlocks(VOTING_PERIOD + 1);
  await (await governor.queue(targets, values, calldatas, descriptionHash)).wait();
  await network.provider.send("evm_increaseTime", [TIMELOCK_MIN_DELAY + 1]);
  await network.provider.send("evm_mine");
  await (
    await governor.execute(targets, values, calldatas, descriptionHash)
  ).wait();

  const chainId = (await ethers.provider.getNetwork()).chainId;
  const blockNumber = await ethers.provider.getBlockNumber();
  const addresses = {
    token: await token.getAddress(),
    timelock: await timelock.getAddress(),
    governor: await governor.getAddress(),
    treasury: await treasury.getAddress(),
  };

  const deployment = {
    network: network.name,
    chainId: Number(chainId),
    blockNumber,
    deployer: deployer.address,
    contracts: {
      GovernanceToken: addresses.token,
      TimelockController: addresses.timelock,
      DAOGovernor: addresses.governor,
      Treasury: addresses.treasury,
    },
    parameters: {
      VOTING_DELAY,
      VOTING_PERIOD,
      PROPOSAL_THRESHOLD,
      QUORUM_FRACTION,
      TIMELOCK_MIN_DELAY,
    },
  };

  const demo = {
    proposalId: proposalId.toString(),
    title,
    description,
    txHash: proposeTx.hash,
    voteTxHashes,
    voters: voters.map((voter) => voter.address),
    votes: {
      againstVotes: againstVotes.toString(),
      forVotes: forVotes.toString(),
      abstainVotes: abstainVotes.toString(),
    },
    treasuryValue: (await treasury.value()).toString(),
  };

  writeJson(path.join(__dirname, "..", "deployments", "localhost.json"), deployment);
  writeJson(
    path.join(__dirname, "..", "deployments", "localhost-demo.json"),
    demo
  );
  updateFrontendLocalEnv(addresses);

  console.log("\nLocal demo complete.");
  console.log("Governor:", addresses.governor);
  console.log("Proposal ID:", proposalId.toString());
  console.log("For votes:", forVotes.toString());
  console.log("Treasury value:", (await treasury.value()).toString());
  console.log("Updated frontend/.env.local for chain 31337.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
